### ISSUE TITLE
Please update for CLion 2021.3

### ISSUE THREAD

**Issue by pgorgon-hem** [marcin-bukowiecki/regdebug#11]
Plugin is not compatibile with latest CLion. Maybe it only needs recompilation

**Comment by marcin-bukowiecki** [comment]
Updated. It will be available for download within 2 business days but you can install it manually from here https://plugins.jetbrains.com/plugin/17203-regdebug/versions/stable/149357

**Comment by pgorgon-hem** [comment]
Thank you very much!
